openapi: "3.0.2"
info:
  title: GA4GH Discovery Search API
  description: Definition of GA4GH Discovery Search API
  termsOfService: https://www.ga4gh.org/
  contact:
    email: rishi.nag@ga4gh.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.1.0"
servers: []
security: []
paths:
  /datasets:
    get:
      summary: List datasets
      description: List all datasets exposed by this Search Node.
      operationId: listDatasets
      responses:
        '200':
          description: The list of available datasets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListDatasetsResponse"
        '500':
          description: An unexpected error occurred
  /dataset/{dataset_id}:
    get:
      summary: Get a dataset
      description: Returns the first page of the dataset identified by dataset_id.
      operationId: getDataset
      parameters:
        - name: dataset_id
          in: path
          description: Unique Dataset ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The first page of the requested dataset
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataset"
        '404':
          description: The requested dataset is not available
        '500':
          description: An unexpected error occurred
  /search:
    post:
      summary: (Placeholder) Perform a search
      description: Optional operation that accepts a query and returns a dataset
      operationId: search
      responses:
        '404':
          description: This server does not implement the search operation
components:
  schemas:
    ListDatasetsResponse:
      required:
        - datasets
      type: object
      properties:
        datasets:
          type: array
          items:
            $ref: "#/components/schemas/DatasetInfo"
      additionalProperties: false
    DatasetInfo:
      required:
        - id
        - schema
      type: object
      properties:
        id:
          type: string
          description: Dataset ID
        location:
          type: string
          description: Dataset absolute or relative location
          format: uri
        description:
          type: string
          description: Optional dataset description
        schema:
          $ref: "http://json-schema.org/draft-07/schema#"
      description: |
        Describes a dataset hosted by this search node.
    Dataset:
      required:
        - objects
        - schema
      type: object
      properties:
        schema:
          $ref: "http://json-schema.org/draft-07/schema#"
        objects:
          type: array
          description: Page of JSON values, each adhering to the schema given in the "schema" property
          items:
            # Each item must conform to the schema provided in the "schema" section of this Dataset.
            # Not sure if this constraint can be expressed in OpenAPI 3.0.
            type: object
        pagination:
          $ref: "#/components/schemas/Pagination"
      description: A paginated collection of tabular data
    Pagination:
      type: object
      properties:
        next_page_url:
          type: string
          description: URL pointing to the next page of the same dataset. Null or absent on last page.
          format: uri
        previous_page_url:
          type: string
          description: URL pointing to the previous page of the same dataset. Null or absent on first page.
          format: uri
